main:
  - name: Communication
    identifier: communication
    weight: 100
    url: https://sivasub.com/
    params:
      header: Connect with me through various platforms.
      icon:
        vendor: font-awesome-solid
        name: comments

  - name: Documentation
    parent: communication
    url: https://sivasub.com/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The documentation.

  - name: GitHub
    parent: communication
    url: https://github.com/siva-sub
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: LinkedIn
    parent: communication
    url: https://www.linkedin.com/in/sivasub987/
    weight: 12
    params:
      icon:
        vendor: fab
        name: linkedin
        color: #0077b5
      description: Connect with me on LinkedIn.

  - name: Gmail
    parent: communication
    url: mailto:Sivasub987@gmail.com
    weight: 13
    params:
      icon:
        vendor: font-awesome-solid
        name: envelope
        color: #D44638
      description: Send me an email.

  - name: WhatsApp
    parent: communication
    url: https://api.whatsapp.com/send?phone=6598272558&text=Hi%20Siva%20👋%2C%20I%20saw%20your%20profile%20and%20wanted%20to%20connect%20with%20you.
    weight: 14
    params:
      icon:
        vendor: font-awesome-brands
        name: whatsapp
        color: green
      description: Contact me on WhatsApp for queries.
