name = "Sivasub's Blog and Portfolio Theme"
license = "MIT"
licenselink = "https://github.com/siva-sub/theme/blob/main/LICENSE"
description = "Sivasubramanian Ramanathan's Blog and Portfolio"
homepage = "https://github.com/siva-sub/theme"
demosite = "https://sivasub.com/"
tags = [
    "blog",
    "portfolio",
    "bootstrap",
    "dark",
    "dark mode",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "Sivasubramanian Ramanathan"
homepage = "https://sivasub.com/"
